# Generated by Django 5.2.9 on 2026-01-06 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='biography',
            field=models.CharField(blank=True, max_length=300, verbose_name='biography'),
        ),
    ]
