# Generated by Django 5.2.9 on 2026-01-19 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_biography'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='biography',
            field=models.CharField(blank=True, max_length=500, verbose_name='biography'),
        ),
    ]
