# Generated by Django 5.2.9 on 2026-01-04 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogpost_options_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='is published'),
        ),
    ]
