# Generated by Django 5.2.9 on 2026-01-21 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blogpost_likes_count_like_blogpost_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='likes_count',
        ),
    ]
