# Generated by Django 5.2.9 on 2026-02-01 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_blogpost_likes_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='views',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
