# Generated by Django 5.2.9 on 2026-02-01 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_blogpost_views'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='views',
            new_name='view_count',
        ),
    ]
