# Generated by Django 5.2.9 on 2026-02-19 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_rename_views_blogpost_view_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='view_count',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
    ]
