# Generated by Django 5.2.9 on 2026-02-27 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_category_blogpost_blogposts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='blogposts',
            field=models.ManyToManyField(related_name='blogposts', to='blog.category'),
        ),
    ]
