# Generated by Django 5.2.9 on 2026-02-27 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_blogpost_blogposts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='blogposts',
            new_name='categories',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
