# Generated by Django 5.2.9 on 2026-02-27 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_blogpost_blogposts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='blogposts',
            new_name='categories',
        ),
    ]
