# Generated by Django 5.2.9 on 2026-03-02 19:10

from django.db import migrations
from django.db import models
from django.utils.text import slugify

def populate_blogpost_slugs(apps, schema_editor):
    BlogPost = apps.get_model('blog', 'BlogPost')
    for blogpost in BlogPost.objects.filter(slug__isnull=True):
        original_slug = slugify(blogpost.title)
        unique_slug = original_slug
        counter = 1
        while BlogPost.objects.filter(slug=unique_slug).exists():
            unique_slug = f'{original_slug}-{counter}'
            counter += 1
        BlogPost.objects.filter(id=blogpost.id).update(slug=unique_slug)

class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_blogpost_slug_alter_category_name'),
    ]

    operations = [
        migrations.RunPython(populate_blogpost_slugs),
        migrations.AlterField(
            'blogpost',
            'slug',
            field=models.SlugField(unique=True, blank=True, null=False, max_length=130)
        ),
    ]
