# Generated by Django 5.2.9 on 2026-03-06 08:16

from django.db import migrations, models
from django.utils import timezone

def populate_published_date_field(apps, schema_editor):
    BlogPost = apps.get_model('blog', 'BlogPost')
    BlogPost.objects.filter(published_date__isnull=True).update(published_date=timezone.now())

class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20260302_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='published date'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(blank=True, max_length=130, null=True),
        ),
        migrations.RunPython(
            populate_published_date_field,
        ),
    ]
