# Generated by Django 5.2.9 on 2026-03-06 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_blogpost_published_date_alter_blogpost_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ('-published_date',), 'verbose_name': 'Blog Post', 'verbose_name_plural': 'Blog Posts'},
        ),
    ]
