# Generated by Django 5.2.9 on 2026-06-03 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_alter_blogpost_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='thumbnail',
            field=models.ImageField(blank=True, default='', null=True, upload_to='blogposts/thumbnails/'),
        ),
    ]
