name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
      POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
      DJANGO_DEBUG: ${{ secrets.DJANGO_DEBUG }}
      DJANGO_ALLOWED_HOSTS: ${{ secrets.DJANGO_ALLOWED_HOSTS }}
      DJANGO_PORT: ${{ secrets.DJANGO_PORT }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      

    steps:
    - uses: actions/checkout@v4
    - name: Launch tests
      run: |
        SUPABASE_URL=${{ secrets.SUPABASE_URL }} \
        SUPABASE_KEY=${{ secrets.SUPABASE_KEY }} \
        docker compose -f compose.test.yaml up --build --abort-on-container-exit
