name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Launch tests
      run: |
        SUPABASE_URL=${{ secrets.SUPABASE_URL }} \
        SUPABASE_KEY=${{ secrets.SUPABASE_KEY }} \
        docker compose -f compose.test.yaml up --build --abort-on-container-exit
